import { Todo } from "../hooks/useFetch";


/**
 * Interface to define the structure of the filtered todos.
 * It contains two arrays of Todo items: completed and pending.
 *
 * @interface FilteredTodos
 * @property {Todo[]} completedTodos - List of completed todos.
 * @property {Todo[]} pendingTodos - List of pending todos.
 */
interface FilteredTodos {
  completedTodos: Todo[];
  pendingTodos: Todo[];
}


/**
 * Filters a list of todos into two categories: completed and pending.
 * It separates the todos into two arrays based on their `completed` status.
 *
 * @param {Todo[]} todos - The array of Todo items to be filtered.
 * @returns {FilteredTodos} - An object containing two arrays: `completedTodos` and `pendingTodos`.
 *
 * @example
 * const todos = [{ id: 1, todo: 'Finish homework', completed: true }];
 * const { completedTodos, pendingTodos } = filterTodos(todos);
 */

export const filterTodos = (todos: Todo[]): FilteredTodos => {
  const completedTodos = todos.filter((todo) => todo.completed);
  const pendingTodos = todos.filter((todo) => !todo.completed);

  return { completedTodos, pendingTodos };
};

/**
 * Generates a random 2-digit number between 10 and 99.
 * The number is generated by picking a random value in the specified range.
 *
 * @returns {number} - A random 2-digit number between 10 and 99.
 *
 * @example
 * const randomNum = generateRandom2DigitNumber();
 */


export const generateRandom2DigitNumber = (): number => {
  return Math.floor(10 + Math.random() * 90);
};
